import { before, beforeEach, after, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { initializeTestEnvironment, assertFails, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { getDoc, setDoc, doc } from 'firebase/firestore';
import { experienceWrite, experiencePreferences, experienceCollections, experienceContinue, playlistTitles } from '../lib/server/experience';
import type { AuthenticatedRequestUser as Actor } from '../lib/server/auth';
assert.match(process.env.FIRESTORE_EMULATOR_HOST||'',/^(127\.0\.0\.1|localhost):\d+$/);
const projectId='demo-afrobooks-watch';const app=initializeApp({projectId});const db=getFirestore(app);let env:RulesTestEnvironment;
const reader:Actor={uid:'reader',role:'buyer',status:'active',email:null};const other:Actor={...reader,uid:'other'};const admin:Actor={...reader,uid:'admin',role:'admin'};
const action=(who:Actor,action:string,data:unknown)=>experienceWrite(who,{action,data});
const draft={id:'collection',title:'Stories from home',description:'A book and a recording.',published:true,items:[{kind:'book',id:'book'},{kind:'audio',id:'audio'}]};
before(async()=>{env=await initializeTestEnvironment({projectId,firestore:{rules:readFileSync('firestore.rules','utf8')}});});
beforeEach(async()=>{await env.clearFirestore();for(const user of [reader,other,admin])await db.doc(`users/${user.uid}`).set(user);await db.doc('books/book').set({title:'Book',status:'live',authorName:'Author',language:'Tigrinya',price:199});await db.doc('audioTitles/audio').set({title:'Audio',creatorName:'Musician',status:'published',ready:true,language:'English',durationSeconds:100,priceCents:199,privateSecret:'never expose'});await db.doc('watchVideos/video').set({title:'Film',status:'published',durationSeconds:100,priceCents:0,privateSecret:'never expose'});});
after(async()=>{await env.cleanup();await deleteApp(app);});
test('playlists and preferences are account-owned, bounded and never expose protected metadata',async()=>{
  await action(reader,'playlist',{id:'favorites',name:'Favourites',titleIds:['audio']});await action(reader,'languages',{languages:['Tigrinya','English']});
  assert.equal((await experiencePreferences(other)).playlists.length,0);assert.equal((await experiencePreferences(reader)).playlists[0].name,'Favourites');
  await assert.rejects(action(reader,'playlist',{id:'bad',name:'Bad',titleIds:['../private']}));
  await assert.rejects(action(reader,'playlist',{id:'bad',name:'Bad',titleIds:['audio','audio']}));
  await assert.rejects(action(reader,'languages',{languages:Array(16).fill('English')}));
  const titles=await playlistTitles(reader);assert.equal(titles.items[0].title,'Audio');assert.doesNotMatch(JSON.stringify(titles),/privateSecret|never expose|url|token/i);
  assert.equal((await db.doc('audioEntitlements/reader/titles/audio').get()).exists,false);
  await assertFails(getDoc(doc(env.authenticatedContext('other').firestore(),'experiencePreferences/reader')));
  await assertFails(setDoc(doc(env.authenticatedContext('reader').firestore(),'experiencePreferences/reader'),{languages:['forged']}));
  await action(reader,'delete_playlist',{id:'favorites'});assert.equal((await experiencePreferences(reader)).playlists.length,0);
});
test('collections require admin, published titles, mixed formats; removals disappear without granting purchases',async()=>{
  await assert.rejects(action(reader,'collection',draft),/Administrator/);
  await assert.rejects(action(admin,'collection',{...draft,items:[{kind:'audio',id:'audio'}]}),/two titles/);
  await action(admin,'collection',draft);assert.equal((await experienceCollections(reader)).collections.length,1);
  await db.doc('audioTitles/audio').update({status:'removed'});const publicCollections=await experienceCollections(reader);assert.equal(publicCollections.collections[0].items.length,1);
  await assert.rejects(action(admin,'collection',draft),/published titles/);
  await action(admin,'collection',{...draft,published:false});assert.equal((await experienceCollections(reader)).collections.length,0);
  await assertFails(setDoc(doc(env.authenticatedContext('reader').firestore(),'storyCollections/forged'),draft));
  await action(admin,'delete_collection',{id:'collection'});assert.equal((await experienceCollections(admin,true)).collections.length,0);
});
test('continue shelf sorts all media by recency and removes finished, refunded or inaccessible titles',async()=>{
  await db.doc('readingProgress/reader_book').set({userId:'reader',bookId:'book',percentComplete:40,isFinished:false,lastReadAt:Timestamp.fromMillis(2000)});
  await db.doc('library/reader_book').set({bookId:'book'});
  await db.doc('watchStates/reader/videos/video').set({seconds:50,updatedAt:3000});
  await db.doc('audioStates/reader/titles/audio').set({seconds:20,updatedAt:1000});await db.doc('audioEntitlements/reader/titles/audio').set({status:'active'});
  const result=await experienceContinue(reader);assert.deepEqual(result.items.map(item=>item.kind),['video','book','audio']);assert.equal(result.items[1].href,'/read/book');
  assert.equal((await experienceContinue(other)).items.length,0);
  await db.doc('library/reader_book').delete();await db.doc('audioEntitlements/reader/titles/audio').update({status:'refunded'});await db.doc('watchStates/reader/videos/video').update({seconds:100});
  assert.equal((await experienceContinue(reader)).items.length,0);
});
