import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash, X509Certificate } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const javaHome = process.env.JAVA_HOME;
const sdk = process.env.ANDROID_HOME;
if (!javaHome || !sdk) throw new Error('Set JAVA_HOME and ANDROID_HOME before signing.');
const extension = process.platform === 'win32' ? '.exe' : '';
const java = path.join(javaHome, 'bin', 'java' + extension);
const keytool = path.join(javaHome, 'bin', 'keytool' + extension);
const jarsigner = path.join(javaHome, 'bin', 'jarsigner' + extension);
const keyDirectory = process.env.AFROBOOKS_SIGNING_DIR || path.join(os.homedir(), '.android', 'afrobooks');
const keyPath = path.join(keyDirectory, 'afrobooks-upload.jks');
const secrets = JSON.parse(fs.readFileSync(path.join(keyDirectory, 'signing-secrets.json'), 'utf8'));
if (!fs.existsSync(keyPath)) throw new Error('The original upload key is missing. Restore the private backup; do not generate a replacement.');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'android/twa-manifest.json'), 'utf8'));
if (!/^\d+\.\d+\.\d+$/.test(manifest.appVersionName)) throw new Error('Use a numeric major.minor.patch release version.');
const output = path.join(root, 'dist/android');
fs.mkdirSync(output, { recursive: true });
const bundle = path.join(output, `afrobooks-${manifest.appVersionName}.aab`);
const apk = path.join(output, `afrobooks-${manifest.appVersionName}.apk`);
const options = { windowsHide: true, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, AFROBOOKS_STORE_PASSWORD: secrets.storePassword, AFROBOOKS_KEY_PASSWORD: secrets.keyPassword } };

const certificate = execFileSync(keytool, ['-exportcert', '-rfc', '-keystore', keyPath, '-alias', secrets.alias, '-storepass:env', 'AFROBOOKS_STORE_PASSWORD'], options);
const fingerprint = new X509Certificate(certificate).fingerprint256;
if (!manifest.fingerprints.some(item => item.value === fingerprint)) throw new Error('Upload certificate does not match the Android project.');
execFileSync(jarsigner, ['-keystore', keyPath, '-storepass:env', 'AFROBOOKS_STORE_PASSWORD', '-keypass:env', 'AFROBOOKS_KEY_PASSWORD', '-sigalg', 'SHA256withRSA', '-digestalg', 'SHA-256', '-signedjar', bundle, path.join(root, 'android/app/build/outputs/bundle/release/app-release.aab'), secrets.alias], options);
const verification = execFileSync(jarsigner, ['-verify', bundle], options);
if (!verification.includes('jar verified')) throw new Error('Bundle signature verification failed.');
const apksigner = path.join(sdk, 'build-tools/36.0.0/lib/apksigner.jar');
execFileSync(java, ['-jar', apksigner, 'sign', '--ks', keyPath, '--ks-key-alias', secrets.alias, '--ks-pass', 'env:AFROBOOKS_STORE_PASSWORD', '--key-pass', 'env:AFROBOOKS_KEY_PASSWORD', '--out', apk, path.join(root, 'android/app/build/outputs/apk/release/app-release-unsigned.apk')], options);
execFileSync(java, ['-jar', apksigner, 'verify', apk], options);
fs.writeFileSync(path.join(output, 'afrobooks-upload-certificate.pem'), certificate);
const files = [bundle, apk].map(file => ({ name: path.basename(file), bytes: fs.statSync(file).size, sha256: createHash('sha256').update(fs.readFileSync(file)).digest('hex') }));
const info = { packageId: manifest.packageId, versionName: manifest.appVersionName, versionCode: manifest.appVersionCode, targetSdk: 36, uploadCertificateSha256: fingerprint, files };
fs.writeFileSync(path.join(output, 'release-info.json'), JSON.stringify(info, null, 2) + '\n');
console.log(JSON.stringify(info, null, 2));
